name: opensarlab-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  # For documentation
  - mkdocs
  - mkdocs-material=6.2
  - mkdocs-material-extensions
  - pip:
      # For documentation
      - mkdocs-asf-theme>=0.2.3
      - mkdocs-redirects
      - mkdocs-section-index
      - mkdocstrings
      - mkdocs-macros-plugin
