name: opensarlab-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  # For documentation
  - mkdocs=1.5.3
  - mkdocs-material=9.4.2
  - requests
  - pip:
      # For documentation
      - mkdocs-asf-theme==0.3.0
      - mkdocs-redirects
      - mkdocs-section-index
      - mkdocstrings
      - mkdocstrings-python
      - mkdocs-macros-plugin
