name: opensarlab-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - texlive-core
  - latexmk 
  - mystmd
  - myst-nb
  - myst-parser      
  - pip
  - requests
  - pip:
      # For documentation
      - jupyter-book==2.0.0a1