site_name: OpenSARLab-Docs
site_url: https://opensarlab-docs.asf.alaska.edu/
site_author: ASF OpenSARLab Team
site_description: The Alaska Satellite Facility's OpenSARLab

theme:
  name: asf-theme
  icon:
    repo: fontawesome/brands/github-alt

extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ASFOpenSARLab

repo_url: https://github.com/ASFOpenSARLab
repo_name: ASF OpenSARLab
edit_uri: ''

nav:
  - Home: index.md
  - Troubleshooting Guide: user-guides/troubleshooting_guide.md
  - User Guide:
    - user.md
    - Configuring Multi-Factor Authentication: user-guides/mfa.md
    - Running Jupyter Notebook: user-guides/how_to_run_a_notebook.md
    - Conda Environments: user-guides/conda_environments.md
    - Installing Software in OpenSARLab: user-guides/installing_software_in_OpenSARLab.md
    - OpenSARLab Servers and Kernels: user-guides/restarting_server_and_kernel.md
    - Jupyter Magic Commands: user-guides/jupyter_magic.md
    - OpenSARLab Terminal: user-guides/OpenSARLab_terminal.md
    - OpenSARLab Account Details: user-guides/OpenSARLab_environment.md
    - Git in OpenSARLab: user-guides/git_in_OpenSARLab.md
    - S3 Bucket Access in OpenSARLab: user-guides/s3_buckets.md
    - Jupyter Notebook Extensions: user-guides/jupyter_notebook_extensions.md
    - Best Practices for Writing Notebooks: user-guides/class_notebooks_best_practices.md
    - Logging Out and Server Shutdown: user-guides/logging_out_and_server_shutdown.md
  - Developer Guide:
    - System Diagram: assets/system_diagrams/OpenSARLab_system_diagram_June_2021.png
    - Deploy OpenSARLab to AWS: dev-guides/deploy_OpenSARLab.md
    - Destroy Deployments: dev-guides/destroy_deployment.md
    - Conda Environment Options: dev-guides/conda_environments.md
    - Notifications: dev-guides/notifications.md
    - Troubelshooting Guide: dev-guides/troubleshooting.md
    - Custom Mintpy Conda Build Instructions: dev-guides/mintpy_conda.md
  - Release Notes:
    - June 2021: release-notes/release_06-2021.md
    - October 2021: release-notes/release_10-2021.md
    - February 2022: release-notes/release_02-2022.md
    - February 2023: release-notes/release_02-2023.md
    - February 2024: release-notes/release_02-2024.md
