site_name: OpenSARlab-Docs
site_url: https://opensarlab-docs.asf.alaska.edu/
site_author: ASF OpenSARlab Team
site_description: The Alaska Satellite Facility's OpenSARlab

theme:
  name: asf-theme
#  logo:
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.instant

repo_url: https://github.com/ASFOpenSARlab
repo_name: ASF OpenSARlab
edit_uri: ''

nav:
  - Home: index.md
  - Troubleshooting Guide: user-guides/troubleshooting_guide.md
  - User Guide:
    - user.md
    - Jupyter Notebook Intro: user-guides/jupyter_notebook_intro.md
    - Running Jupyter Notebook: user-guides/how_to_run_a_notebook.md
    - Best Practices for Writing Notebooks: user-guides/class_notebooks_best_practices.md
    - Jupyter Magic Commands: user-guides/jupyter_magic.md
    - OpenSARlab Account Details: user-guides/OpenSARlab_environment.md
    - Git in OpenSARlab: user-guides/git_in_OpenSARlab.md
    - OpenSARlab Terminal: user-guides/OpenSARlab_terminal.md
    - OpenSARlab Servers and Kernels: user-guides/restarting_server_and_kernel.md
    - Jupyter Notebook Extensions: user-guides/jupyter_notebook_extensions.md
    - Installing Software in OpenSARlab: user-guides/installing_software_in_OpenSARlab.md
    - Conda Environments: user-guides/conda_environments.md
    - Logging Out and Server Shutdown: user-guides/logging_out_and_server_shutdown.md
  - Developer Guide:
    - System Diagram: assets/system_diagrams/OpenSARlab_system_diagram_June_2021.png
    - Deploy OpenSARlab to AWS: dev-guides/deploy_OpenSARlab.md
    - Troubelshooting Guide: dev-guides/troubleshooting.md
  - Release Notes:
    - June 2021: release-notes/release_06-2021.md
