name: Deploy to Github.io

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    name: Build site and deploy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          path: opensarlab-docs

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: opensarlab-docs
          environment-file: opensarlab-docs/environment.yml

      - name: Deploy test website
        shell: bash -l {0}
        run: |
          cd docs
          if [ -f CNAME ]; then rm CNAME; fi
          myst build --all
          cd ..
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git fetch origin gh-pages
          git checkout gh-pages
          mkdir -p opensarlab-docs
          rm -rf opensarlab-docs/public
          rm -rf opensarlab-docs/content
          cp -r docs/_build/site/public opensarlab-docs
          cp -r docs/_build/site/content opensarlab-docs
          git add opensarlab-docs
          git commit -m "Deploy updated dev site"
          git push origin gh-pages --force
          