name: Deploy to Github.io

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    name: Build site and deploy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          path: opensarlab-docs

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: opensarlab-docs
          environment-file: opensarlab-docs/environment.yml

      - name: Deploy test website
        shell: bash -l {0}
        run: |
      - name: Deploy test website
        shell: bash -l {0}
        run: |
          cd opensarlab-docs
          if [ -f docs/CNAME ]; then rm docs/CNAME; fi
          jupyter-book build ./docs/myst.yml
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git fetch origin gh-pages
          git checkout gh-pages
          git rm -rf .
          cp -r _build/site/public/* .
          git add .
          git commit -m "Deploy updated Jupyter Book site"
          git push origin gh-pages --force