name: Deploy to Github.io

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build site and deploy
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          path: opensarlab-docs
          
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: osl-docs
          environment-file: opensarlab-docs/environment.yml
      
      - uses: actions/checkout@v2
        with:
          repository: ASFOpenSARlab/ASFOpenSARlab.github.io
          path: ASFOpenSARlab.github.io
          token: ${{ secrets.OPENSARLAB_BOT_ACCESS }}

      - name: deploy to github.io
        shell: bash -l {0}
        run: |
          cd ASFOpenSARlab.github.io
          mkdocs gh-deploy  --force --config-file ../opensarlab-docs/mkdocs.yml --remote-branch main
